name: test_and_lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: black-ruff-mypy
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    # Installing all dependencies and not just the linters as mypy needs them for type checking
    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
    - name: Run linters
      run: |
        hatch run test